[theme]

# Primary accent for interactive elements
primaryColor = '#953C3C'

# Background color for the main content area
backgroundColor = '#FFF9F0'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#c19485'

# Color used for almost all text
textColor = '#6a3e36'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"